# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.4.0"
slug: example
description: Example add-on
url: "https://github.com/habuild/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
Ingress: 8099
ingress_entry: /hassio
ingress_stream:	false
panel_icon:	mdi:puzzle-star
panel_title: Addons
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/habuild/{arch}-addon-example"
